export const columnLabelsByResource: Record<string, Record<string, string>> = {
  authors: {
    AuthorID: 'ID',
    Name: 'Nombre',
    NationalityName: 'Nacionalidad',
    LiteraryGenreName: 'Género literario',
    Status: 'Estado',
    Photo: 'Foto',
  },
  books: {
    isbn: 'ISBN',
    coverUrl: 'Portada',
    title: 'Título',
    categoryName: 'Categoría',
    publisherName: 'Editorial',
    languageCode: 'Idioma',
    releaseDate: 'Fecha publicación',
    status: 'Estado',
    id: 'ID',
  },
  courses: {
    CourseID: 'ID',
    Name: 'Nombre',
    Level: 'Nivel',
    Description: 'Descripción',
    Status: 'Estado',
  },
  loans: {
    code: 'Código',
    readerCode: 'Cód. lector',
    readerFullName: 'Lector',
    loanDate: 'Fecha préstamo',
    itemCount: 'Ejemplares',
    statusCounts: 'Estados',
    id: 'ID',
  },
  reservations: {
    code: 'Código',
    readerCode: 'Cód. lector',
    readerFullName: 'Lector',
    copyCode: 'Cód. ejemplar',
    reservationDate: 'Fecha reserva',
    status: 'Estado',
    id: 'ID',
  },
  fines: {
    code: 'Código',
    loanCode: 'Cód. préstamo',
    copyCode: 'Cód. ejemplar',
    amount: 'Monto',
    daysLate: 'Días retraso',
    status: 'Estado',
    issuedAt: 'Fecha emisión',
    id: 'ID',
  },
  payments: {
    code: 'Código',
    fineCount: 'Multas',
    readerCode: 'Cód. lector',
    readerFullName: 'Lector',
    amount: 'Monto',
    paymentDate: 'Fecha pago',
    method: 'Método',
    id: 'ID',
  },
  publishers: {
    PublisherID: 'ID',
    Name: 'Nombre',
    NationalityName: 'Nacionalidad',
    LiteraryGenreName: 'Género literario',
    Status: 'Estado',
    Photo: 'Foto',
  },
  students: {
    StudentID: 'ID',
    DNI: 'DNI',
    FirstName: 'Nombres',
    LastName: 'Apellidos',
    Phone: 'Teléfono',
    Email: 'Correo electrónico',
    Status: 'Estado',
  },
  users: {
    UserID: 'ID',
    Username: 'Nombre de usuario',
    Email: 'Correo electrónico',
    FirstName: 'Nombres',
    LastName: 'Apellidos',
    Role: 'Rol',
    ProfilePhoto: 'Foto',
  },
}

export function getColumnLabel(resource: string, columnId: string): string {
  return columnLabelsByResource[resource]?.[columnId] ?? columnId
}
