export const columnLabelsByResource: Record<string, Record<string, string>> = {
  authors: {
    id: 'ID',
    photoUrl: 'Foto',
    name: 'Nombre',
    nationalityCode: 'Nacionalidad',
    nationalityName: 'Nacionalidad',
    birthDate: 'Fecha nacimiento',
    status: 'Estado',
  },
  books: {
    id: 'ID',
    isbn: 'ISBN',
    coverUrl: 'Portada',
    title: 'Título',
    categoryName: 'Categoría',
    publisherName: 'Editorial',
    languageCode: 'Idioma',
    languageName: 'Idioma',
    loanedCopies: 'Prestados',
    availableCopies: 'Disponibles',
    status: 'Estado',
  },
  copies: {
    id: 'ID',
    code: 'Código',
    bookCoverUrl: 'Portada libro',
    bookTitle: 'Libro',
    shelfCode: 'Estantería',
    shelfFloor: 'Piso',
    locationName: 'Ubicación',
    status: 'Estado',
    condition: 'Condición',
  },
  categories: {
    id: 'ID',
    name: 'Nombre',
    level: 'Nivel',
    description: 'Descripción',
    status: 'Estado',
  },
  loans: {
    id: 'ID',
    code: 'Código',
    readerCode: 'Cód. lector',
    readerFullName: 'Lector',
    loanDate: 'Fecha préstamo',
    itemCount: 'Ejemplares',
    statusCounts: 'Estados',
  },
  reservations: {
    id: 'ID',
    code: 'Código',
    readerCode: 'Cód. lector',
    readerFullName: 'Lector',
    copyCode: 'Cód. ejemplar',
    reservationDate: 'Fecha reserva',
    status: 'Estado',
  },
  fines: {
    id: 'ID',
    code: 'Código',
    loanCode: 'Cód. préstamo',
    copyCode: 'Cód. ejemplar',
    amount: 'Monto',
    daysLate: 'Días retraso',
    status: 'Estado',
    issuedAt: 'Fecha emisión',
  },
  payments: {
    id: 'ID',
    code: 'Código',
    fineCount: 'Multas',
    readerCode: 'Cód. lector',
    readerFullName: 'Lector',
    amount: 'Monto',
    paymentDate: 'Fecha pago',
    method: 'Método',
  },
  publishers: {
    id: 'ID',
    photoUrl: 'Foto',
    name: 'Nombre',
    nationalityCode: 'Nacionalidad',
    nationalityName: 'Nacionalidad',
    website: 'Sitio web',
    address: 'Dirección',
    status: 'Estado',
  },
  students: {
    StudentID: 'ID',
    DNI: 'DNI',
    FirstName: 'Nombres',
    LastName: 'Apellidos',
    Phone: 'Teléfono',
    Email: 'Correo electrónico',
    Status: 'Estado',
  },
  users: {
    UserID: 'ID',
    Username: 'Nombre de usuario',
    Email: 'Correo electrónico',
    FirstName: 'Nombres',
    LastName: 'Apellidos',
    Role: 'Rol',
    ProfilePhoto: 'Foto',
  },
}

export function getColumnLabel(resource: string, columnId: string): string {
  return columnLabelsByResource[resource]?.[columnId] ?? columnId
}
