/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthRestablecerContraseChar241aIndexRouteImport } from './routes/_auth/restablecer-contraseña/index'
import { Route as AuthRecuperarContraseChar241aIndexRouteImport } from './routes/_auth/recuperar-contraseña/index'
import { Route as AuthIniciarSesionIndexRouteImport } from './routes/_auth/iniciar-sesion/index'
import { Route as AppUbicacionesIndexRouteImport } from './routes/_app/ubicaciones/index'
import { Route as AppTrabajadoresIndexRouteImport } from './routes/_app/trabajadores/index'
import { Route as AppRolesIndexRouteImport } from './routes/_app/roles/index'
import { Route as AppLibrosIndexRouteImport } from './routes/_app/libros/index'
import { Route as AppLectoresIndexRouteImport } from './routes/_app/lectores/index'
import { Route as AppEjemplaresIndexRouteImport } from './routes/_app/ejemplares/index'
import { Route as AppEditorialesIndexRouteImport } from './routes/_app/editoriales/index'
import { Route as AppCentroDeAyudaIndexRouteImport } from './routes/_app/centro-de-ayuda/index'
import { Route as AppCategoriasIndexRouteImport } from './routes/_app/categorias/index'
import { Route as AppAutoresIndexRouteImport } from './routes/_app/autores/index'
import { Route as AppAjustesIndexRouteImport } from './routes/_app/ajustes/index'
import { Route as AppPrestamosReservasRouteImport } from './routes/_app/prestamos/reservas'
import { Route as AppPrestamosPagosRouteImport } from './routes/_app/prestamos/pagos'
import { Route as AppPrestamosMultasRouteImport } from './routes/_app/prestamos/multas'
import { Route as AppPrestamosEnCursoRouteImport } from './routes/_app/prestamos/en-curso'
import { Route as AppPrestamosDevueltosRouteImport } from './routes/_app/prestamos/devueltos'
import { Route as AppAjustesNotificacionesRouteImport } from './routes/_app/ajustes/notificaciones'
import { Route as AppAjustesCuentaRouteImport } from './routes/_app/ajustes/cuenta'
import { Route as AppAjustesAparienciaRouteImport } from './routes/_app/ajustes/apariencia'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthRestablecerContraseChar241aIndexRoute =
  AuthRestablecerContraseChar241aIndexRouteImport.update({
    id: '/restablecer-contraseña/',
    path: '/restablecer-contraseña/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthRecuperarContraseChar241aIndexRoute =
  AuthRecuperarContraseChar241aIndexRouteImport.update({
    id: '/recuperar-contraseña/',
    path: '/recuperar-contraseña/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthIniciarSesionIndexRoute = AuthIniciarSesionIndexRouteImport.update({
  id: '/iniciar-sesion/',
  path: '/iniciar-sesion/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppUbicacionesIndexRoute = AppUbicacionesIndexRouteImport.update({
  id: '/ubicaciones/',
  path: '/ubicaciones/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrabajadoresIndexRoute = AppTrabajadoresIndexRouteImport.update({
  id: '/trabajadores/',
  path: '/trabajadores/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRolesIndexRoute = AppRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLibrosIndexRoute = AppLibrosIndexRouteImport.update({
  id: '/libros/',
  path: '/libros/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLectoresIndexRoute = AppLectoresIndexRouteImport.update({
  id: '/lectores/',
  path: '/lectores/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEjemplaresIndexRoute = AppEjemplaresIndexRouteImport.update({
  id: '/ejemplares/',
  path: '/ejemplares/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEditorialesIndexRoute = AppEditorialesIndexRouteImport.update({
  id: '/editoriales/',
  path: '/editoriales/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCentroDeAyudaIndexRoute = AppCentroDeAyudaIndexRouteImport.update({
  id: '/centro-de-ayuda/',
  path: '/centro-de-ayuda/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCategoriasIndexRoute = AppCategoriasIndexRouteImport.update({
  id: '/categorias/',
  path: '/categorias/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAutoresIndexRoute = AppAutoresIndexRouteImport.update({
  id: '/autores/',
  path: '/autores/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjustesIndexRoute = AppAjustesIndexRouteImport.update({
  id: '/ajustes/',
  path: '/ajustes/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrestamosReservasRoute = AppPrestamosReservasRouteImport.update({
  id: '/prestamos/reservas',
  path: '/prestamos/reservas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrestamosPagosRoute = AppPrestamosPagosRouteImport.update({
  id: '/prestamos/pagos',
  path: '/prestamos/pagos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrestamosMultasRoute = AppPrestamosMultasRouteImport.update({
  id: '/prestamos/multas',
  path: '/prestamos/multas',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrestamosEnCursoRoute = AppPrestamosEnCursoRouteImport.update({
  id: '/prestamos/en-curso',
  path: '/prestamos/en-curso',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrestamosDevueltosRoute = AppPrestamosDevueltosRouteImport.update({
  id: '/prestamos/devueltos',
  path: '/prestamos/devueltos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjustesNotificacionesRoute = AppAjustesNotificacionesRouteImport.update({
  id: '/ajustes/notificaciones',
  path: '/ajustes/notificaciones',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjustesCuentaRoute = AppAjustesCuentaRouteImport.update({
  id: '/ajustes/cuenta',
  path: '/ajustes/cuenta',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAjustesAparienciaRoute = AppAjustesAparienciaRouteImport.update({
  id: '/ajustes/apariencia',
  path: '/ajustes/apariencia',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/ajustes/apariencia': typeof AppAjustesAparienciaRoute
  '/ajustes/cuenta': typeof AppAjustesCuentaRoute
  '/ajustes/notificaciones': typeof AppAjustesNotificacionesRoute
  '/prestamos/devueltos': typeof AppPrestamosDevueltosRoute
  '/prestamos/en-curso': typeof AppPrestamosEnCursoRoute
  '/prestamos/multas': typeof AppPrestamosMultasRoute
  '/prestamos/pagos': typeof AppPrestamosPagosRoute
  '/prestamos/reservas': typeof AppPrestamosReservasRoute
  '/ajustes': typeof AppAjustesIndexRoute
  '/autores': typeof AppAutoresIndexRoute
  '/categorias': typeof AppCategoriasIndexRoute
  '/centro-de-ayuda': typeof AppCentroDeAyudaIndexRoute
  '/editoriales': typeof AppEditorialesIndexRoute
  '/ejemplares': typeof AppEjemplaresIndexRoute
  '/lectores': typeof AppLectoresIndexRoute
  '/libros': typeof AppLibrosIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/trabajadores': typeof AppTrabajadoresIndexRoute
  '/ubicaciones': typeof AppUbicacionesIndexRoute
  '/iniciar-sesion': typeof AuthIniciarSesionIndexRoute
  '/recuperar-contraseña': typeof AuthRecuperarContraseChar241aIndexRoute
  '/restablecer-contraseña': typeof AuthRestablecerContraseChar241aIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/ajustes/apariencia': typeof AppAjustesAparienciaRoute
  '/ajustes/cuenta': typeof AppAjustesCuentaRoute
  '/ajustes/notificaciones': typeof AppAjustesNotificacionesRoute
  '/prestamos/devueltos': typeof AppPrestamosDevueltosRoute
  '/prestamos/en-curso': typeof AppPrestamosEnCursoRoute
  '/prestamos/multas': typeof AppPrestamosMultasRoute
  '/prestamos/pagos': typeof AppPrestamosPagosRoute
  '/prestamos/reservas': typeof AppPrestamosReservasRoute
  '/ajustes': typeof AppAjustesIndexRoute
  '/autores': typeof AppAutoresIndexRoute
  '/categorias': typeof AppCategoriasIndexRoute
  '/centro-de-ayuda': typeof AppCentroDeAyudaIndexRoute
  '/editoriales': typeof AppEditorialesIndexRoute
  '/ejemplares': typeof AppEjemplaresIndexRoute
  '/lectores': typeof AppLectoresIndexRoute
  '/libros': typeof AppLibrosIndexRoute
  '/roles': typeof AppRolesIndexRoute
  '/trabajadores': typeof AppTrabajadoresIndexRoute
  '/ubicaciones': typeof AppUbicacionesIndexRoute
  '/iniciar-sesion': typeof AuthIniciarSesionIndexRoute
  '/recuperar-contraseña': typeof AuthRecuperarContraseChar241aIndexRoute
  '/restablecer-contraseña': typeof AuthRestablecerContraseChar241aIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/ajustes/apariencia': typeof AppAjustesAparienciaRoute
  '/_app/ajustes/cuenta': typeof AppAjustesCuentaRoute
  '/_app/ajustes/notificaciones': typeof AppAjustesNotificacionesRoute
  '/_app/prestamos/devueltos': typeof AppPrestamosDevueltosRoute
  '/_app/prestamos/en-curso': typeof AppPrestamosEnCursoRoute
  '/_app/prestamos/multas': typeof AppPrestamosMultasRoute
  '/_app/prestamos/pagos': typeof AppPrestamosPagosRoute
  '/_app/prestamos/reservas': typeof AppPrestamosReservasRoute
  '/_app/ajustes/': typeof AppAjustesIndexRoute
  '/_app/autores/': typeof AppAutoresIndexRoute
  '/_app/categorias/': typeof AppCategoriasIndexRoute
  '/_app/centro-de-ayuda/': typeof AppCentroDeAyudaIndexRoute
  '/_app/editoriales/': typeof AppEditorialesIndexRoute
  '/_app/ejemplares/': typeof AppEjemplaresIndexRoute
  '/_app/lectores/': typeof AppLectoresIndexRoute
  '/_app/libros/': typeof AppLibrosIndexRoute
  '/_app/roles/': typeof AppRolesIndexRoute
  '/_app/trabajadores/': typeof AppTrabajadoresIndexRoute
  '/_app/ubicaciones/': typeof AppUbicacionesIndexRoute
  '/_auth/iniciar-sesion/': typeof AuthIniciarSesionIndexRoute
  '/_auth/recuperar-contraseña/': typeof AuthRecuperarContraseChar241aIndexRoute
  '/_auth/restablecer-contraseña/': typeof AuthRestablecerContraseChar241aIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes/apariencia'
    | '/ajustes/cuenta'
    | '/ajustes/notificaciones'
    | '/prestamos/devueltos'
    | '/prestamos/en-curso'
    | '/prestamos/multas'
    | '/prestamos/pagos'
    | '/prestamos/reservas'
    | '/ajustes'
    | '/autores'
    | '/categorias'
    | '/centro-de-ayuda'
    | '/editoriales'
    | '/ejemplares'
    | '/lectores'
    | '/libros'
    | '/roles'
    | '/trabajadores'
    | '/ubicaciones'
    | '/iniciar-sesion'
    | '/recuperar-contraseña'
    | '/restablecer-contraseña'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes/apariencia'
    | '/ajustes/cuenta'
    | '/ajustes/notificaciones'
    | '/prestamos/devueltos'
    | '/prestamos/en-curso'
    | '/prestamos/multas'
    | '/prestamos/pagos'
    | '/prestamos/reservas'
    | '/ajustes'
    | '/autores'
    | '/categorias'
    | '/centro-de-ayuda'
    | '/editoriales'
    | '/ejemplares'
    | '/lectores'
    | '/libros'
    | '/roles'
    | '/trabajadores'
    | '/ubicaciones'
    | '/iniciar-sesion'
    | '/recuperar-contraseña'
    | '/restablecer-contraseña'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/'
    | '/_app/ajustes/apariencia'
    | '/_app/ajustes/cuenta'
    | '/_app/ajustes/notificaciones'
    | '/_app/prestamos/devueltos'
    | '/_app/prestamos/en-curso'
    | '/_app/prestamos/multas'
    | '/_app/prestamos/pagos'
    | '/_app/prestamos/reservas'
    | '/_app/ajustes/'
    | '/_app/autores/'
    | '/_app/categorias/'
    | '/_app/centro-de-ayuda/'
    | '/_app/editoriales/'
    | '/_app/ejemplares/'
    | '/_app/lectores/'
    | '/_app/libros/'
    | '/_app/roles/'
    | '/_app/trabajadores/'
    | '/_app/ubicaciones/'
    | '/_auth/iniciar-sesion/'
    | '/_auth/recuperar-contraseña/'
    | '/_auth/restablecer-contraseña/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/restablecer-contraseña/': {
      id: '/_auth/restablecer-contraseña/'
      path: '/restablecer-contraseña'
      fullPath: '/restablecer-contraseña'
      preLoaderRoute: typeof AuthRestablecerContraseChar241aIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/recuperar-contraseña/': {
      id: '/_auth/recuperar-contraseña/'
      path: '/recuperar-contraseña'
      fullPath: '/recuperar-contraseña'
      preLoaderRoute: typeof AuthRecuperarContraseChar241aIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/iniciar-sesion/': {
      id: '/_auth/iniciar-sesion/'
      path: '/iniciar-sesion'
      fullPath: '/iniciar-sesion'
      preLoaderRoute: typeof AuthIniciarSesionIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/ubicaciones/': {
      id: '/_app/ubicaciones/'
      path: '/ubicaciones'
      fullPath: '/ubicaciones'
      preLoaderRoute: typeof AppUbicacionesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/trabajadores/': {
      id: '/_app/trabajadores/'
      path: '/trabajadores'
      fullPath: '/trabajadores'
      preLoaderRoute: typeof AppTrabajadoresIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/roles/': {
      id: '/_app/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/libros/': {
      id: '/_app/libros/'
      path: '/libros'
      fullPath: '/libros'
      preLoaderRoute: typeof AppLibrosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/lectores/': {
      id: '/_app/lectores/'
      path: '/lectores'
      fullPath: '/lectores'
      preLoaderRoute: typeof AppLectoresIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ejemplares/': {
      id: '/_app/ejemplares/'
      path: '/ejemplares'
      fullPath: '/ejemplares'
      preLoaderRoute: typeof AppEjemplaresIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/editoriales/': {
      id: '/_app/editoriales/'
      path: '/editoriales'
      fullPath: '/editoriales'
      preLoaderRoute: typeof AppEditorialesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/centro-de-ayuda/': {
      id: '/_app/centro-de-ayuda/'
      path: '/centro-de-ayuda'
      fullPath: '/centro-de-ayuda'
      preLoaderRoute: typeof AppCentroDeAyudaIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/categorias/': {
      id: '/_app/categorias/'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/autores/': {
      id: '/_app/autores/'
      path: '/autores'
      fullPath: '/autores'
      preLoaderRoute: typeof AppAutoresIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ajustes/': {
      id: '/_app/ajustes/'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AppAjustesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prestamos/reservas': {
      id: '/_app/prestamos/reservas'
      path: '/prestamos/reservas'
      fullPath: '/prestamos/reservas'
      preLoaderRoute: typeof AppPrestamosReservasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prestamos/pagos': {
      id: '/_app/prestamos/pagos'
      path: '/prestamos/pagos'
      fullPath: '/prestamos/pagos'
      preLoaderRoute: typeof AppPrestamosPagosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prestamos/multas': {
      id: '/_app/prestamos/multas'
      path: '/prestamos/multas'
      fullPath: '/prestamos/multas'
      preLoaderRoute: typeof AppPrestamosMultasRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prestamos/en-curso': {
      id: '/_app/prestamos/en-curso'
      path: '/prestamos/en-curso'
      fullPath: '/prestamos/en-curso'
      preLoaderRoute: typeof AppPrestamosEnCursoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/prestamos/devueltos': {
      id: '/_app/prestamos/devueltos'
      path: '/prestamos/devueltos'
      fullPath: '/prestamos/devueltos'
      preLoaderRoute: typeof AppPrestamosDevueltosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ajustes/notificaciones': {
      id: '/_app/ajustes/notificaciones'
      path: '/ajustes/notificaciones'
      fullPath: '/ajustes/notificaciones'
      preLoaderRoute: typeof AppAjustesNotificacionesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ajustes/cuenta': {
      id: '/_app/ajustes/cuenta'
      path: '/ajustes/cuenta'
      fullPath: '/ajustes/cuenta'
      preLoaderRoute: typeof AppAjustesCuentaRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/ajustes/apariencia': {
      id: '/_app/ajustes/apariencia'
      path: '/ajustes/apariencia'
      fullPath: '/ajustes/apariencia'
      preLoaderRoute: typeof AppAjustesAparienciaRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAjustesAparienciaRoute: typeof AppAjustesAparienciaRoute
  AppAjustesCuentaRoute: typeof AppAjustesCuentaRoute
  AppAjustesNotificacionesRoute: typeof AppAjustesNotificacionesRoute
  AppPrestamosDevueltosRoute: typeof AppPrestamosDevueltosRoute
  AppPrestamosEnCursoRoute: typeof AppPrestamosEnCursoRoute
  AppPrestamosMultasRoute: typeof AppPrestamosMultasRoute
  AppPrestamosPagosRoute: typeof AppPrestamosPagosRoute
  AppPrestamosReservasRoute: typeof AppPrestamosReservasRoute
  AppAjustesIndexRoute: typeof AppAjustesIndexRoute
  AppAutoresIndexRoute: typeof AppAutoresIndexRoute
  AppCategoriasIndexRoute: typeof AppCategoriasIndexRoute
  AppCentroDeAyudaIndexRoute: typeof AppCentroDeAyudaIndexRoute
  AppEditorialesIndexRoute: typeof AppEditorialesIndexRoute
  AppEjemplaresIndexRoute: typeof AppEjemplaresIndexRoute
  AppLectoresIndexRoute: typeof AppLectoresIndexRoute
  AppLibrosIndexRoute: typeof AppLibrosIndexRoute
  AppRolesIndexRoute: typeof AppRolesIndexRoute
  AppTrabajadoresIndexRoute: typeof AppTrabajadoresIndexRoute
  AppUbicacionesIndexRoute: typeof AppUbicacionesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAjustesAparienciaRoute: AppAjustesAparienciaRoute,
  AppAjustesCuentaRoute: AppAjustesCuentaRoute,
  AppAjustesNotificacionesRoute: AppAjustesNotificacionesRoute,
  AppPrestamosDevueltosRoute: AppPrestamosDevueltosRoute,
  AppPrestamosEnCursoRoute: AppPrestamosEnCursoRoute,
  AppPrestamosMultasRoute: AppPrestamosMultasRoute,
  AppPrestamosPagosRoute: AppPrestamosPagosRoute,
  AppPrestamosReservasRoute: AppPrestamosReservasRoute,
  AppAjustesIndexRoute: AppAjustesIndexRoute,
  AppAutoresIndexRoute: AppAutoresIndexRoute,
  AppCategoriasIndexRoute: AppCategoriasIndexRoute,
  AppCentroDeAyudaIndexRoute: AppCentroDeAyudaIndexRoute,
  AppEditorialesIndexRoute: AppEditorialesIndexRoute,
  AppEjemplaresIndexRoute: AppEjemplaresIndexRoute,
  AppLectoresIndexRoute: AppLectoresIndexRoute,
  AppLibrosIndexRoute: AppLibrosIndexRoute,
  AppRolesIndexRoute: AppRolesIndexRoute,
  AppTrabajadoresIndexRoute: AppTrabajadoresIndexRoute,
  AppUbicacionesIndexRoute: AppUbicacionesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(AppRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthIniciarSesionIndexRoute: typeof AuthIniciarSesionIndexRoute
  AuthRecuperarContraseChar241aIndexRoute: typeof AuthRecuperarContraseChar241aIndexRoute
  AuthRestablecerContraseChar241aIndexRoute: typeof AuthRestablecerContraseChar241aIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthIniciarSesionIndexRoute: AuthIniciarSesionIndexRoute,
  AuthRecuperarContraseChar241aIndexRoute: AuthRecuperarContraseChar241aIndexRoute,
  AuthRestablecerContraseChar241aIndexRoute: AuthRestablecerContraseChar241aIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(AuthRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
